# Data exploration with Pandas

## Setup Notebook and Kernel
The file is placed in the folder `day_72/` and the kernel used is the uv .venv inside the root folder `100-DAYS-OF-PYTHON/`
<div style="background:Gainsboro; border-left:4px solid DodgerBlue; padding:10px; padding-left:10 px; width:800px; border-radius:6px;">
<strong style="color:DodgerBlue;">ⓘ Note</strong>
<p style="margin-bottom:5px;">
The choice to go with a local kernel is because Google Colab forces steps to work from its platform.<br>  
Pandas works mainly with CPU so for now no need to use GPUs and the code can be committed.
</p>
</div>

In [80]:
import pandas as pd

df = pd.read_csv("salaries_by_college_major.csv")
df.head() # Show the top 5 rows of the dataframe

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

## Exploring data

### Shape of the table and column names

In [81]:
df.shape, df.columns

((51, 6),
 Index(['Undergraduate Major', 'Starting Median Salary',
        'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
        'Mid-Career 90th Percentile Salary', 'Group'],
       dtype='str'))

### NaN (Not A Number) check
Use the `isna()` combined with `any()` that works with boolean data with `axis=1` that goes in row-wise direction (`axis=0` goes column-wise).

In [82]:
df.isna().tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [83]:
df.isna().any()

Undergraduate Major                  False
Starting Median Salary                True
Mid-Career Median Salary              True
Mid-Career 10th Percentile Salary     True
Mid-Career 90th Percentile Salary     True
Group                                 True
dtype: bool

Create a mask with `.any()` and `axis=1`. While `df.isna().any(axis=1)` gives back a **Series of booleans** with the same length as the dataframe, it means it can be used as a mask for the dataframe.  
It means we can have a table where only the row that has at least (any) columns with value NaN will appear.

In [84]:
df[df.isna().any(axis=1)]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

## Edit rows
Use `dropna()` to drop the last row that simply refers to the source and it is not usable.

In [85]:
clean_df = df.dropna()
# Check the tail to confirm the row was dropped
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

## Accessing data

### Find College Major with the Highest **Starting Salary**

#### Locate the highest value for the Starting Salary and the index
The `.max()` alone returns for a Series just a value, in this case `np.float64(74300.0)`.  
Instead `.idxmax()` return the index of the row with the highest value

In [86]:
clean_df['Starting Median Salary'].max()

np.float64(74300.0)

In [87]:
max_salary_starting = clean_df['Starting Median Salary'].idxmax()
print(max_salary_starting)

43

#### Locate the name of the Undergraduate Major
Use `.loc` (location) to check the property of a particular row

In [88]:
clean_df['Undergraduate Major'].loc[max_salary_starting]

'Physician Assistant'

In [89]:
# With one square brackets it shows a series, with two it forces to a 2D dimension table (list of series) and as such shows a table
clean_df.loc[[max_salary_starting]]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM

### Find College Major with the Lowest **Starting Salary**

#### Locate the lowest value for the Starting Salary and the index

In [90]:
print(clean_df['Starting Median Salary'].min())
min_salary_starting = clean_df['Starting Median Salary'].idxmin()
print(min_salary_starting)

34000.0
49

#### Locate the name of the Undergraduate Major

In [91]:
clean_df['Undergraduate Major'].loc[min_salary_starting]

'Spanish'

In [92]:
clean_df.loc[[min_salary_starting]]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

### Find College Major with the Highest **Mid-Carrer Salary**

#### Locate the highest value for the Mid-Career Salary and the index

In [93]:
print(clean_df['Mid-Career Median Salary'].max())
max_salary_mid = clean_df['Mid-Career Median Salary'].idxmax()
print(max_salary_mid)

107000.0
8

#### Locate the name of the Undergraduate Major

In [94]:
clean_df['Undergraduate Major'].loc[max_salary_mid]

'Chemical Engineering'

In [95]:
clean_df.loc[[max_salary_mid]]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM

### Find College Major with the Lowest **Mid-Career Salary**

#### Locate the lowest value for the Mid-Career Salary and the index

In [96]:
print(clean_df['Mid-Career Median Salary'].min())
min_salary_mid = clean_df['Mid-Career Median Salary'].idxmin()
print(min_salary_mid)

52000.0
18

#### Locate the name of the Undergraduate Major

In [97]:
clean_df['Undergraduate Major'].loc[min_salary_mid]

'Education'

In [98]:
clean_df.loc[[min_salary_mid]]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
18,Education,34900.0,52000.0,29300.0,102000.0,HASS